services:
  rpi-bme280-to-prom:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: rpi-bme280-to-prom
    environment:
      - GPIOZERO_PIN_FACTORY=rpigpio
      - TZ=America/Chicago
      - MQTT_BROKER=192.168.0.175
      - MQTT_PORT=1883
      - MQTT_USER=
      - MQTT_PW=
      - MQTT_TOPIC="dzicave/pimedia/sensors"
    ports:
      - 8001:8000
    privileged: true
    restart: unless-stopped
