services:
  bmporter:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: bmporter
    hostname: bmporter
    environment:
      - GPIOZERO_PIN_FACTORY=rpigpio
      - TZ=America/Chicago
      - MQTT_BROKER=
      - MQTT_PORT=1883
      - MQTT_USER=
      - MQTT_PW=
      - MQTT_TOPIC="topic/name/whatever"
    ports:
      - 8000:8000
    privileged: true
    restart: unless-stopped
